CREATE DATABASE IF NOT EXISTS FACTURACION_SAMA;

-- CREATE USER 'SAMA_CONCILIA_UPLOADER'@'localhost' IDENTIFIED BY 'Pasw0rd'

-- GRANT ALL PRIVILEGES ON * . * TO 'SAMA_CONCILIA_UPLOADER'@'localhost'

-- -----------------------------------------------------
-- Tabla tb_facturas
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS FACTURACION_SAMA.tb_factura (
    FECHA_DE_AUDITORÍA DATE NOT NULL,
    DOCUMENTO CHAR(40),
    CONSECUTIVO INT NOT NULL,
    NUM_FACTURA_MEDICAMENTO INT NOT NULL,
    NUM_FACTURA_OL INT NOT NULL,
    ESM_FACTURACION INT NOT NULL,
    ESM_FACTURACION_NOMBRE CHAR(125),
    ESM_CODIGO INT NOT NULL,
    ESM_INTERNO INT NOT NULL,
    ESM_NOMBRE CHAR(125),
    ESM_ADSCRITO INT NOT NULL,
    ESM_ADSCRITO_NOMBRE CHAR(125),
    FUERZA_ESM_ADSCRITO INT NOT NULL,
    FUERZA_ESM_NOMBRE_ADSCRITO CHAR(125),
    FUERZA_ESM INT NOT NULL,
    FUERZA_ESM_NOMBRE CHAR(125),
    TIPO_DISPENSACION CHAR(125),
    CODIGO_AUTORIZACION CHAR(125),
    DOCUMENTO_FECHA_FORMULACION DATE NOT NULL,
    DOCUMENTO_FECHA_TRANSACCION DATE NOT NULL,
    TIPO_MEDICAMENTO_NOMBRE CHAR(50),
    TIPO_FORMULA_NOMBRE CHAR(50),
    AFILIADO_CODIGO INT(12),
    AFILIADO_NOMBRE CHAR(125),
    FUERZA_FACTURA_NOMBRE CHAR(125),
    TIPO_VINCULACION_NOMBRE CHAR(50),
    CODIGO_MEDICAMENTO CHAR(50),
    CODIGO_MEDICAMENTO_HOMIC CHAR(50),
    DESC_MEDICAMENTO_REFERENCIA CHAR(125),
    DESC_MEDICAMENTO_GENERICO CHAR(125),
    F039_CANTIDAD_PEDIDA INT NOT NULL,
    CANTIDAD_DESPACHADA INT NOT NULL,
    PRECIO_UNITARIO FLOAT NOT NULL,
    VALOR_ADECUACION FLOAT NOT NULL,
    SUBTOTAL_ANTES_IVA FLOAT NOT NULL,
    VALOR_EXCLUIDO FLOAT NOT NULL,
    VALOR_GRAVADO FLOAT NOT NULL,
    VALOR_IVA FLOAT NOT NULL,
    VALOR_FACTURA_MEDICAMENTOS FLOAT NOT NULL,
    VALOR_INTERMEDIACION FLOAT NOT NULL,
    VALOR_IVA_INTERM FLOAT NOT NULL,
    VALOR_FACTURA_OL FLOAT NOT NULL,
    TOTAL FLOAT NOT NULL,
    TOTAL_REPORTADO_A_SAMA FLOAT NOT NULL,
    DIFERENCIA_ENTRE_SAMA_Y_DROSERVICIO FLOAT NOT NULL,
    LOTE CHAR(50),
    FECHA_VENCIMIENTO DATE NOT NULL,
    INVIMA CHAR(50),
    DOSIS FLOAT NOT NULL,
    TIEMPO_DOSIS FLOAT NOT NULL,
    CONCENTRACION CHAR(15),
    ESM_GENERA_FORMULA INT NOT NULL,
    ESM_GENERA_FORMULA_NOMBRE CHAR(125),
    CIE10 CHAR(50),
    CIE10_NOMBRE CHAR(50),
    MEDICO_CODIGO INT NOT NULL,
    MEDICO_NOMBRE CHAR(125),
    TIPO_FORMULA CHAR(125),
    TIRILLA INT NOT NULL,
    DOCUMENTO_NUMERO_ITEM INT NOT NULL,
    LABORATORIO_CODIGO INT NOT NULL,
    LABORATORIO_NOMBRE CHAR(125),
    VR_FACTURACION FLOAT NOT NULL,
    ANTICIPO_50 FLOAT NOT NULL,
    SEGUNDO_DESEMBOLSO FLOAT NOT NULL,
    PAGO_CONCILIACION_1 FLOAT NULL,
    PAGO_CONCILIACION_2 FLOAT NULL,
    SALDO FLOAT NOT NULL,
    PRIMARY KEY (DOCUMENTO)
);

-- -----------------------------------------------------
-- Tabla tb_glosa
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS FACTURACION_SAMA.tb_glosa (
    ID INT NOT NULL AUTO_INCREMENT,
    CODIGO_GLOSA CHAR(50),
    DESCRIPCION_GLOSA VARCHAR(500),
    VR_MEDICAMENTO FLOAT,
    INTERMEDIACION FLOAT,
    IVA_INTERMEDIACION FLOAT,
    IVA FLOAT ,
    UNIDOSIS FLOAT,
    TOTAL FLOAT,
    VALOR_A_PAGAR FLOAT,
    ESTADO CHAR(15),
    PRIMARY KEY (ID)
);

-- -----------------------------------------------------
-- Tabla tb_respuesta_opl
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS FACTURACION_SAMA.tb_respuesta_opl(
    RESPUESTA_OPL_ID INT NOT NULL AUTO_INCREMENT,
    GLOSA_ID INT NOT NULL,
    RESPUESTA_OPL VARCHAR(500),
    OBSERVACION VARCHAR(500),
    VALOR_ACEPTADO FLOAT NOT NULL,
    VALOR_NO_ACEPTADO FLOAT NOT NULL,
    PRIMARY KEY (RESPUESTA_OPL_ID),
    FOREIGN KEY (GLOSA_ID) REFERENCES FACTURACION_SAMA.tb_glosa(ID)
);

CREATE TABLE IF NOT EXISTS FACTURACION_SAMA.tb_CONCILIACION(
    CONCILIACION_ID INT NOT NULL AUTO_INCREMENT,
    GLOSA_ID INT NOT NULL,
    RESPUESTA_OPL VARCHAR(500),
    OBSERVACION VARCHAR(500),
    VALOR_ACEPTADO FLOAT NOT NULL,
    VALOR_NO_ACEPTADO FLOAT NOT NULL,
    CODIGO_GLOSA CHAR(50),
    VALOR_OBJETADO FLOAT NOT NULL,
    VALOR_OBJETADO_ACEPTADO_CONCILIACION FLOAT NOT NULL,
    OBSERVACION_GLOSA VARCHAR(500),
    VALOR_SOPORTADO FLOAT,
    OBSERVACION_GLOSA_SOPORTADA_SAMA VARCHAR(500),
    VALOR_RATIFICADO_EN_CONCILIACION FLOAT,
    OBSERVACION_GLOSA_DEFINITIVA VARCHAR(500),
    VALOR_NO_CONCILIADO_SEGUNDA_INSTANCIA FLOAT,
    OBSERVACION_GLOSA_SEGUNDA_INSTANCIA VARCHAR(500),
    VALOR_SUBTOTAL_MEDICAMENTO_A_PAGAR FLOAT,
    VALOR_GASTO_DE_OPL_A_PAGAR FLOAT,
    VALOR_IVA_OPL_A_PAGAR FLOAT,
    VALOR_IVA_DEL_MEDICAMENTO_A_PAGAR FLOAT,
    VALOR_ADECUACION_A_PAGAR FLOAT,
    VALOR_A_PAGAR_CONCILIADO FLOAT,
    ESTADO CHAR(50),
    PRIMARY KEY (CONCILIACION_ID),
    FOREIGN KEY (GLOSA_ID) REFERENCES FACTURACION_SAMA.tb_glosa(ID)
);